- fastimage.gemspec
- lib/fastimage.rb
- lib/fastimage/fbr.rb
- test/test.rb
Hi,
this patch add an per-request proxy option so we can easily do this
```ruby
FastImage.size("http://farm4.static.flickr.com/3023/3047236863_9dce98b836.jpg", proxy: 'http://my-proxy-host.com:7777')
FastImage.type("http://farm4.static.flickr.com/3023/3047236863_9dce98b836.jpg", proxy: 'http://my-proxy-host.com:7777')
```
Also maybe you should exclude `Gemfile.lock` from the repo?
> add options[:proxy] as a per request proxy config

- README.textile
- lib/fastimage.rb
- test/test.rb
Fix #51 allow accessing request header content-length information.
> Add reader for request header content-length

- README.textile
- lib/fastimage.rb
Hi,
I use FastImage to request hosts which require a User-Agent HTTP header. This commit makes it possible to specify additional HTTP headers for each request.
```ruby
FastImage.size("http://example.nowhere/image.jpg", :http_header => {'User-Agent' => 'Fake Browser'})
```
I didnt find a way to write a reasonable test using FakeWeb. It seems like there is no way to differentiate between HTTP headers. Let me know if you know a way.
Regards
> Support additional HTTP headers

- lib/fastimage.rb
- test/fixtures/test.xml
- test/test.rb
Fixes https://github.com/sdsykes/fastimage/issues/55 .
As xml files are not always svg's, this PR adds further verifications to check that it's really a svg file.
> raise UnknownImageType when file is non-svg xml

- .travis.yml
Also use containerized builds for Travis CI.
Uses the latests stables of Ruby 2.1.x, 2.2.x and 2.3.x.
> Add Ruby 2.2.4, 2.3.0 to Travis. Update to 2.1.8.

- lib/fastimage.rb
- test/test.rb
When an error occured when extracting dimensions, rewinding would be skipped and the code would jump straight to "rescue" statements. We want that the IO is always rewinded, even in case of errors.
Note that this doesn't affect the return value of the method, because the return value of a method-level "ensure" is always ignored by Ruby.
> Always rewind the given IO

- lib/fastimage.rb
In case of 'ice' file type when neither 1 or 2 is found it should raise `UnknownImageType` but it didn't, probably due to the method not being 100% DRY.
This commit fixes both issues at once
> Improve parse_type UnknownImageType detection

- README.textile
Originally, this update was to prevent Textile from changing single
quotes into directional quotes in a code snippet under the Features
header.
The snippet pertains to setting additional HTTP headers:
```
:http_header => {'User-Agent' => 'Fake Browser'}
```
To maintain consistency, all code phrases found under the Features
header were wrapped in @ symbols.
A couple minor typos were also corrected.
> Enclose README code phrases in Textile code markup

- lib/fastimage.rb
- test/test.rb
Currently fastimage doesn't support redirects with protocol relative urls. Steps to repro the issue - 
```
2.2.1 :001 > require 'fastimage'
=> true
2.2.1 :002 > url = "https://play.vidyard.com/osHCgNMQPWmwNCzcaVmnfW.jpg"
=> "https://play.vidyard.com/osHCgNMQPWmwNCzcaVmnfW.jpg"
2.2.1 :003 > FastImage.type(url)
=> nil
```
Since the "Location" header in the response has a protocol relative url ("//cdn.vidyard.com/thumbnails/obaGtqzifX3Tb_M77d8m-g/e36a970cd907fb19356e10.jpg"), fastimage treats it as a relative url as there is no scheme and it fails to follow the redirect.
According to the first answer and the comments in this [post](http://stackoverflow.com/questions/9646407/two-forward-slashes-in-a-url-src-href-attribute), it seems like protocol relative urls is an accepted standard. I hope …
> Handle protocol relative urls

- test/test.rb
It's not necessary: http://www.rubyinside.com/why-using-require-rubygems-is-wrong-1478.html
One less line of code to maintain :)
> Remove rubygems require from test.rb

- lib/fastimage.rb
`frozen_string_literal` is a Ruby 2.3 feature (see https://www.ruby-lang.org/en/news/2015/12/25/ruby-2-3-0-released/ ) to make string literals faster if you  deal them as immutable objects.
Note that this has no effect on pre 2.3.
> add frozen_string_literal: true

- lib/fastimage.rb
- test/test.rb
The URL https://flic.kr/p/Vv4Und redirects as:
```
https://www.flickr.com/photo.gne?short=Vv4Und
https://www.flickr.com/photo.gne?rb=1&short=Vv4Und
https://www.flickr.com/photos/always_praveen/35115848582/
```
and causes
```plain
URI::InvalidComponentError: bad component(expected absolute path component): /photo.gne?rb=1&short=Vv4Und
```
> better redirect handling

- lib/fastimage.rb
- test/test.rb
If input io has been read lib return nil first time.
> Should work for readed ios

- lib/fastimage.rb
So that the below works:
`FastImage.size("https://pbs.twimg.com/media/DWOxDNiWsAAg46x.jpg", proxy: "https://user:password@proxy.com:1234")`
Thanks for a great gem!
٩( ᐛ )و
> Support proxies that require a username and password

- README.textile
Hey!
I was wondering if Ruby 1.9.3 is really still officially supported since the tests are not being run on these versions since 0dcffe126eb77144a2e96e25981883b74d455cb3.
> Use SVG Travis CI badge

- lib/fastimage.rb
- test/fixtures/test2.xml
- test/test.rb
Testing for files beginning with `<s` isn't enough to determine if a file is a SVG. It should at least start with `<svg` otherwise an XML starting with `<soap:Envelope` will be detected as SVG.
> Avoid detecting arbitrary XML as SVG

- lib/fastimage.rb
- test/test.rb
Fix ArgumentError thrown when the response for the URL does not contain header `Location`
Got this when trying to use this gem to check and report invalid images from a long list of image URLs
> Fix handling of redirect response without Location header

- lib/fastimage.rb
There are GIFs with multiple frames and zero delay, but also GIFs with
a single frame and positive delay. The old algorithm failed for this
kind of images.
> Use frames count instead of delay to check animated GIFs

- README.textile
- lib/fastimage.rb
1. `new_string = @read_fiber.resume if new_string.is_a? Net::ReadAdapter` is the actual fix.
2. it was hidden by `rescue NoMethodError`
3. it was also hiding the "invalid data uri" test exception
4. another fix: reraising the `UnknownImageType` was destroying the original backtrace/cause
> force_encoding was called on Net::ReadAdapter when url is webmocked

- lib/fastimage.rb
- test/fixtures/test6.svg
- test/test.rb
We have encountered SVG files that begin with a BOM character.
https://en.wikipedia.org/wiki/Byte_order_mark
If the first two chars are the start of a BOM character, it will fetch additional characters as it attempts to find the opening `<svg` tag (the same as if two spaces are the first chars in the file, etc).
> Identify SVG files that start with a BOM character

- lib/fastimage.rb
- test/test.rb
> Handle nil being passed as uri

- lib/fastimage.rb
- test/fixtures/test7.svg
- test/test.rb
At least one older version of Adobe Illustrator adds a bunch of XML entity tags at the start of the file, meaning that the existing check to see if a file is an SVG gives up before finding the `svg` tag
> Handle SVG files that have extra cruft at the start

- lib/fastimage.rb
> Ensure nil is returned from dead fibers

- fastimage.gemspec
base64 is no longer the default gem from Ruby 3.4
https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/
On Ruby 3.3, we could see the warning:
```ruby
warning: base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec.
```
From Ruby 3.4, we will get the error:
```ruby
Failure/Error: require 'base64'
LoadError:
cannot load such file -- base64
```
add `base64` gem as a dependency to gemspec
>  Add base64 as a dependency explicitly for Ruby 3.4.0 support
